version: "3.8"

services:
  web:
    build: .
    ports:
      - "9090:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - prostock-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbprostock
      MYSQL_USER: prostock_user
      MYSQL_PASSWORD: prostock_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dbprostock_sql.sql:/docker-entrypoint-initdb.d/dbprostock_sql.sql
    networks:
      - prostock-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "9091:80"
    depends_on:
      - db
    networks:
      - prostock-network

volumes:
  mysql_data:

networks:
  prostock-network:
    driver: bridge
